### ISSUE TITLE
Only relatively prime to n is needed

### ISSUE THREAD

**Issue by vanship82** [actuallyachraf/gomorph#2]
https://github.com/actuallyachraf/gomorph/blob/a9bc4d1b0ab0368a0577c071862505d7dfb04a47/gaillier/gaillier.go#L95

Here you use rand.Prime() to generate a random prime number. In fact, in encryption of Paillier, only a random relatively prime number to the public key N is needed. It can make the encryption much faster.

**Comment by actuallyachraf** [comment]
thanks for this remark and sorry for the late replies, if you would like to make a PR you are very welcome I will merge it ASAP.
I am currently doing some research on HE to see how I can expand the scope of this library.
